package service

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/pilotworks/dockor/internal/models"
	"github.com/pilotworks/dockor/internal/repository"
)

type CaddyService struct {
	repo        *repository.Repository
	caddyDir    string
	caddyFile   string
	adminURL    string
	globalEmail string
	httpClient  *http.Client
	mu          sync.RWMutex
	lastError   string
}

func NewCaddyService(repo *repository.Repository, dataDir string, adminURL string, globalEmail string) *CaddyService {
	caddyDir := filepath.Join(dataDir, "caddy")
	_ = os.MkdirAll(caddyDir, 0755)

	if adminURL == "" {
		adminURL = "http://localhost:2019"
	}
	adminURL = strings.TrimRight(adminURL, "/")

	return &CaddyService{
		repo:        repo,
		caddyDir:    caddyDir,
		caddyFile:   filepath.Join(caddyDir, "Caddyfile"),
		adminURL:    adminURL,
		globalEmail: globalEmail,
		httpClient: &http.Client{
			Timeout: 5 * time.Second,
		},
	}
}

// GenerateCaddyfile creates a standardized Caddyfile configuration from active proxy routes
func (s *CaddyService) GenerateCaddyfile(routes []models.ProxyRoute) string {
	var sb strings.Builder

	sb.WriteString("# Dockor Caddy Configuration\n")
	sb.WriteString("# Automatically generated by Dockor Reverse Proxy Engine. Do not edit directly.\n\n")

	// Global options block
	sb.WriteString("{\n")
	if s.globalEmail != "" {
		sb.WriteString(fmt.Sprintf("\temail %s\n", s.globalEmail))
	}
	sb.WriteString("\tadmin localhost:2019\n")
	sb.WriteString("}\n\n")

	var activeCount int
	for _, r := range routes {
		if !r.Enabled {
			continue
		}
		activeCount++

		domain := strings.TrimSpace(r.Domain)
		if domain == "" {
			continue
		}

		target := strings.TrimSpace(r.TargetURL)
		if target == "" {
			continue
		}

		// Normalize target upstream address
		upstream := target
		if strings.HasPrefix(strings.ToLower(upstream), "http://") {
			upstream = strings.TrimPrefix(upstream, "http://")
		}

		switch r.SSLMode {
		case models.SSLModeDisabled:
			// Plain HTTP only
			if !strings.HasPrefix(domain, "http://") && !strings.HasPrefix(domain, "http://:") {
				sb.WriteString(fmt.Sprintf("http://%s {\n", domain))
			} else {
				sb.WriteString(fmt.Sprintf("%s {\n", domain))
			}
			sb.WriteString(fmt.Sprintf("\treverse_proxy %s\n", upstream))
			sb.WriteString("}\n\n")

		case models.SSLModeInternal:
			// Local trusted certificate / self-signed internal CA
			sb.WriteString(fmt.Sprintf("%s {\n", domain))
			sb.WriteString("\ttls internal\n")
			sb.WriteString(fmt.Sprintf("\treverse_proxy %s\n", upstream))
			sb.WriteString("}\n\n")

		case models.SSLModeCustom:
			// Custom TLS configuration
			sb.WriteString(fmt.Sprintf("%s {\n", domain))
			sb.WriteString(fmt.Sprintf("\treverse_proxy %s\n", upstream))
			sb.WriteString("}\n\n")

		case models.SSLModeLetsEncrypt:
			fallthrough
		default:
			// Automatic public HTTPS via Let's Encrypt / ZeroSSL
			sb.WriteString(fmt.Sprintf("%s {\n", domain))
			if r.Email != "" {
				sb.WriteString(fmt.Sprintf("\ttls %s\n", r.Email))
			}
			sb.WriteString(fmt.Sprintf("\treverse_proxy %s\n", upstream))
			sb.WriteString("}\n\n")
		}
	}

	if activeCount == 0 {
		// Provide default placeholder listener so Caddy daemon runs smoothly
		sb.WriteString(":80 {\n")
		sb.WriteString("\trespond \"Dockor Reverse Proxy is running (No active routes configured)\" 200\n")
		sb.WriteString("}\n")
	}

	return sb.String()
}

// Sync writes Caddyfile to disk and instructs Caddy Admin API to hot-reload routes
func (s *CaddyService) Sync(ctx context.Context) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	routes, err := s.repo.ListProxyRoutes(ctx)
	if err != nil {
		s.lastError = fmt.Sprintf("Failed to list routes: %v", err)
		return fmt.Errorf("failed to list proxy routes: %w", err)
	}

	caddyfileContent := s.GenerateCaddyfile(routes)

	// 1. Ensure directory exists and write Caddyfile to disk
	if err := os.MkdirAll(s.caddyDir, 0755); err != nil {
		s.lastError = fmt.Sprintf("Failed to create caddy directory: %v", err)
		return fmt.Errorf("failed to create caddy directory: %w", err)
	}

	if err := os.WriteFile(s.caddyFile, []byte(caddyfileContent), 0644); err != nil {
		s.lastError = fmt.Sprintf("Failed to write Caddyfile: %v", err)
		return fmt.Errorf("failed to write Caddyfile: %w", err)
	}

	// 2. Hot-reload Caddy via Admin API (POST /load)
	loadURL := fmt.Sprintf("%s/load", s.adminURL)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, loadURL, bytes.NewBufferString(caddyfileContent))
	if err != nil {
		s.lastError = fmt.Sprintf("Failed to create reload request: %v", err)
		return fmt.Errorf("failed to create reload request: %w", err)
	}
	req.Header.Set("Content-Type", "text/caddyfile")

	resp, err := s.httpClient.Do(req)
	if err != nil {
		// Caddy daemon might not be running locally (e.g. standalone or external container)
		s.lastError = fmt.Sprintf("Caddy Admin API unavailable (%s): %v. Configuration saved to disk.", s.adminURL, err)
		log.Printf("[Caddy Proxy] Notice: %s", s.lastError)
		return nil
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		body, _ := io.ReadAll(resp.Body)
		s.lastError = fmt.Sprintf("Caddy Admin API returned %d: %s", resp.StatusCode, string(body))
		log.Printf("[Caddy Proxy] Warning: %s", s.lastError)
		return fmt.Errorf("caddy reload error (%d): %s", resp.StatusCode, string(body))
	}

	s.lastError = ""
	log.Printf("[Caddy Proxy] Hot reload succeeded: synchronized %d active route(s)", len(routes))
	return nil
}

// GetStatus checks the reachability of the Caddy Admin API and reports configuration status
func (s *CaddyService) GetStatus(ctx context.Context) (*models.CaddyStatus, error) {
	s.mu.RLock()
	lastErr := s.lastError
	s.mu.RUnlock()

	routes, err := s.repo.ListProxyRoutes(ctx)
	if err != nil {
		return nil, err
	}

	activeCount := 0
	for _, r := range routes {
		if r.Enabled {
			activeCount++
		}
	}

	// Ping Admin API /config/
	configURL := fmt.Sprintf("%s/config/", s.adminURL)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, configURL, nil)
	if err != nil {
		return &models.CaddyStatus{
			Running:      false,
			AdminURL:     s.adminURL,
			ConfigPath:   s.caddyFile,
			ActiveRoutes: activeCount,
			LastError:    err.Error(),
		}, nil
	}

	resp, err := s.httpClient.Do(req)
	if err != nil {
		return &models.CaddyStatus{
			Running:      false,
			AdminURL:     s.adminURL,
			ConfigPath:   s.caddyFile,
			ActiveRoutes: activeCount,
			LastError:    lastErr,
		}, nil
	}
	defer resp.Body.Close()

	return &models.CaddyStatus{
		Running:      resp.StatusCode == http.StatusOK,
		AdminURL:     s.adminURL,
		ConfigPath:   s.caddyFile,
		ActiveRoutes: activeCount,
		LastError:    lastErr,
	}, nil
}

// GetCaddyfile returns the raw generated Caddyfile configuration
func (s *CaddyService) GetCaddyfile(ctx context.Context) (string, error) {
	routes, err := s.repo.ListProxyRoutes(ctx)
	if err != nil {
		return "", err
	}
	return s.GenerateCaddyfile(routes), nil
}
